export const UPDATE_USER_PAGE_STATE = "UPDATE_USER_PAGE_STATE";
export const UPDATE_ADVISER_PROPERTY_FILTER_STATE =
  "UPDATE_ADVISER_PROPERTY_FILTER_STATE";
export const CLEAR_PROPERTY_FILTER_STATE = "CLEAR_PROPERTY_FILTER_STATE";
export const UPDATE_LEAD_COUNT = "UPDATE_LEAD_COUNT";
