export const UPDATE_CALL_STATE = "UPDATE_CALL_STATE";
export const RESET_CALL_STATE = "RESET_CALL_STATE";
export const UPDATE_QUE_CALL_STATE = "UPDATE_QUE_CALL_STATE";
export const UPDATE_LOG_CLICK_TIMER = "UPDATE_LOG_CLICK_TIMER";
export const UPDATE_CALL_STATUS = "UPDATE_CALL_STATUS";
export const UPDATE_CALLED_USER_DETAIL = "UPDATE_CALLED_USER_DETAIL";
export const UPDATE_CALL_QUEUE_LIST = "UPDATE_CALL_QUEUE_LIST";
export const UPDATE_QUEUE_LEAD_TITLE = "UPDATE_QUEUE_LEAD_TITLE";
