export default {
  FETCHED_PACKAGE_LIST: "FETCHED_PACKAGE_LIST",
  FETCHED_SERVICES_LIST: "FETCHED_SERVICES_LIST",
  FETCHED_SERVICE_CATEGORIES: "FETCHED_SERVICE_CATEGORIES",
  UPDATE_PROGRESS_FORM_STATE: "UPDATE_PROGRESS_FORM_STATE",
  FETCHED_BUSINESS_PROFILE: "FETCHED_BUSINESS_PROFILE",
};
