export const UPDATE_AGENCY_FILTER_STATE = "UPDATE_AGENCY_FILTER_STATE";
export const UPDATE_AGENCY_LOCATION_FILTER_STATE =
  "UPDATE_AGENCY_LOCATION_FILTER_STATE";
export const UPDATE_SALE_LIST_FILTER_STATE = "UPDATE_SALE_LIST_FILTER_STATE";
