export const UPDATE_PROPERTY_SERVICES = "UPDATE_PROPERTY_SERVICES";
export const UPDATE_COMMUNITY_SERVICES = "UPDATE_COMMUNITY_SERVICES";
export const UPDATE_AMENITY_SERVICES = "UPDATE_AMENITY_SERVICES";
export const UPDATE_PROPERTY_LIST_FILTER = "UPDATE_PROPERTY_LIST_FILTER";
export const UPDATE_PROPERTY_CARE_TYPES = "UPDATE_PROPERTY_CARE_TYPES";
export const UPDATE_PROPERTY_ROOM_TYPES = "UPDATE_PROPERTY_ROOM_TYPES";
